version: "3.8"
name: "C.A.D.S.O.K."
services:

  # Postgres database for order-service
  storage-order-service-pg-db:
    extends:
      file: docker-general-configs.yml
      service: common-config-initial-100m
    image: postgres:14.15-alpine3.20
    container_name: order-service-pg-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - order-service-pg-db_local_data:/var/lib/postgresql/data

  # Postgres database for payment-service
  storage-payment-service-pg-db:
    extends:
      file: docker-general-configs.yml
      service: common-config-initial-100m
    image: postgres:14.15-alpine3.20
    container_name: payment-service-pg-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - payment-service-pg-db_local_data:/var/lib/postgresql/data

  # Postgres database for restaurant-service
  storage-restaurant-service-pg-db:
    extends:
      file: docker-general-configs.yml
      service: common-config-initial-100m
    image: postgres:14.15-alpine3.20
    container_name: restaurant-service-pg-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - restaurant-service-pg-db_local_data:/var/lib/postgresql/data

  # PG Admin for postgres database UI
  storage-pg-admin-postgres-ui:
    extends:
      file: docker-general-configs.yml
      service: common-config-initial-100m
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8088:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  elasticsearch_data:
    driver: local
  order-service-pg-db_local_data:
  payment-service-pg-db_local_data:
  restaurant-service-pg-db_local_data:
  pgadmin-data:
